name: Secret Example

on:
  workflow_dispatch: {}

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Test Secret
        run: |
          echo "Masked Secret:"
          echo ${{ secrets.RACFID_DEV }}
          echo "Secret:"
          echo ${{ secrets.RACFID_DEV }} | sed 's/./& /g'
          echo "Masked Secret:"
          echo ${{ secrets.RACFID_LOCAL }}
          echo "Secret:"
          echo ${{ secrets.RACFID_LOCAL }} | sed 's/./& /g'
       
      
