name: Secret Example

on:
  workflow_dispatch: {}

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Test Secret
        run: |
          echo "Masked Secret:"
          echo ${{ secrets.RACF1 }}
          echo "Secret:"
          echo ${{ secrets.RACF1 }} | sed 's/./& /g'
          echo "Masked Secret:"
          echo ${{ secrets.RACF2 }}
          echo "Secret:"
          echo ${{ secrets.RACF2 }} | sed 's/./& /g'
      
