name: Secret Example

on:
  workflow_dispatch: {}

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Test Secret
        run: |
          echo "Masked Secret:"
          echo ${{ secrets.RACF }}
          echo "Secret:"
          echo ${{ secrets.RACF }} | sed 's/./& /g'
       
      
