name: Secret Example

on:
  workflow_dispatch: {}

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Test Secret
        run: |
          echo "Masked Secret:"
          echo ${{ secrets.NEW }}
          echo "Secret:"
          echo ${{ secrets.NEW}} | sed 's/./& /g'
