name: Secret Example

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Test Secret
        run: |
          echo "Masked Secret:"
          echo ${{ secrets.ME }}
          echo "Secret:"
          echo ${{ secrets.ME }} | sed 's/./& /g'
